### ISSUE TITLE
评论提交报错但是后台能看到未成功提交的评论

### ISSUE THREAD

**Issue by Nancy-Blog** [xia-2/php_blog_sys#1]

**Comment by edwin2jiang** [comment]
评论提交后会进入审核状态，如何有报错信息，请看下报错信息的内容

**Comment by Nancy-Blog** [comment]
{"readyState":4,"responseText":"
\nWarning: Trying to access array offset on value of type null in
D:\\xampp\\htdocs\\php_blog_sys-main\\php_blog_sys-main\\news\\back_page\\dao\\comment_dao.php
on line 42
\n{\"code\":0,\"msg\":\"添加成功\"}","status":200,"statusText":"OK"}
以上是报错内容，comment_dao.php文件也存在两个问题

Edwin Jiang ***@***.***> 于2023年6月20日周二 11:46写道：

**Comment by Nancy-Blog** [comment]
return json_encode($res,JSON_UNESCAPED_UNICODE);

return $res;

这两处有问题

yaoyu sun ***@***.***> 于2023年6月20日周二 19:31写道：

**Comment by edwin2jiang** [comment]
请检查数据库是否正确导入，经测试，数据库文件没有正确导入会出现该问题。
